name: Translate GitBook Content

on:
  push:
    paths:
      - "content/**/*.md"  # Trigger on Markdown file changes

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install openai pyyaml markdown

      # Step 4: Translate content
      - name: Translate content
        run: python scripts/translate.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # Step 5: Commit and push the translated files
      - name: Commit translated files
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add translated/ja
          git commit -m "Add translated files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
